---
 
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart supervisor
  service: name=supervisor enabled=yes state=restarted
