---

- name: Add nginx apt key
  apt_key:
    url='http://nginx.org/keys/nginx_signing.key'
  
- name: Add nginx apt repo
  apt_repository:
    repo="deb http://nginx.org/packages/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename }} nginx"
    update_cache=yes
  
- name: Install Nginx apt package
  apt: pkg=nginx state=latest
  
- name: Disable default servers
  file:
    path=/etc/nginx/conf.d/{{ item.path }}
    state=absent
  with_items:
    - { path: 'default.conf' }
    - { path: 'example_ssl.conf' }

- name: Copy gunincorn configuration file
  copy: src=gunicorn_start.sh dest=/home/cuckoo/cuckoo-1.2/web/ owner=cuckoo group=cuckoo mode=0755

- name: Copy supervisor configuration
  copy: src=cuckoo_super.conf dest=/etc/supervisor/conf.d/ owner=root group=root mode=0644
  notify: restart supervisor 

- name: Copy the Nginx configuration file
  copy: src=cuckoo_web.conf dest=/etc/nginx/conf.d/ owner=root group=root mode=0644
  notify: restart nginx